sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sambit24795/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sambit24795/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker-depl"
  env: "ReactDockerDepl-env"
  bucket_name: "elasticbeanstalk-us-east-2-841357881706"
  bucket_path: "react-docker-depl"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
