sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sambit24795/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sambit24795/docker-react npm run test